FROM quay.io/wildfly/wildfly:28.0.0.Final-jdk17

RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent
ADD build/libs/*.war /opt/jboss/wildfly/standalone/deployments/hillel-servlet.war

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]